### ISSUE TITLE
Puedes usar el matcher .toHaveBeenCalled()

### ISSUE THREAD

**Issue by betsyvies** [mairelis-montilla/LIM014-mdlinks#14]
Te recomiendo que uses el matcher `.toHaveBeenCalled()` porque así te aseguras que tu funciones almenos esta siendo llamada una vez, porque como el test no estamos probando si realmente se está ejecutando. Esta función es especial porque no tiene valor de retorno.

```
describe('isFile', () => {
  it('it is a function', () => {
    expect(typeof isFile).toBe('function');
  });
  it('is files ', () => {
    const listMd = [];
    const pathsDir = [
      `${__dirname}/test/`,
      `${__dirname}/test/test.md`,
      `${__dirname}/test/testDir/test.md`,
      `${__dirname}/test/testDir/test2.md`,
    ];
    expect(isFile(pathsDir, listMd)).toBe();
  });
});
```

**Comment by mairelis-montilla** [comment]
Si con ese test tenia muchas dudas. Lo implementare gracias :heart:
