### ISSUE TITLE
Eliminar console.log como valor de retorno en index.js

### ISSUE THREAD

**Issue by betsyvies** [mairelis-montilla/LIM014-mdlinks#9]
En la linea 13 y 18, veo que tienes `console.log` como valor de retorno, te recomendaría cambiar esto. 
Por ejemplo:
Actual
`return console.log('soy prueba2', elem, stats.isDirectory());`
Cambio
`return 'soy prueba2', elem, stats.isDirectory();`

**Comment by mairelis-montilla** [comment]
LGTM :100:
